## GTM Demo: Fitting a sinusoidal curve
##
## This demo shows the GTM fitting a 1D latent variable model to
## 2D data generated by y = x + 1.25*sin(2*x).

# Generate data: 1D uniform through a nonlinear function
TT <- matrix(3:61 / 20, ncol = 1)
TT <- cbind(TT, TT + 1.25 * sin(2 * TT))

cat("Data: 30 points from y = x + 1.25*sin(2*x)\n")
cat("Fitting 1D GTM with 20 latent nodes, 5 basis functions...\n\n")

# Fit the model
model <- GtmFit(TT, latent_dim = 1, grid_size = 20, n_basis = 5,
                basis_width = 2, n_iter = 15, verbose = TRUE)

cat("\n")
print(model)

# Plot the mapped curve over the data
Y <- model$Y  # mapped points in data space

plot(TT[, 1], TT[, 2], col = "red", pch = 21,
     xlim = range(TT[, 1]) + c(-0.3, 0.3),
     ylim = range(TT[, 2]) + c(-0.3, 0.3),
     xlab = "x", ylab = "y",
     main = "GTM fit: 1D latent space")
lines(Y[order(Y[, 1]), 1], Y[order(Y[, 1]), 2], col = "green", lwd = 2)
points(Y[, 1], Y[, 2], pch = 23, col = "green", bg = "green", cex = 0.8)
# Draw variance circles
r <- sqrt(1 / model$beta)
symbols(Y[, 1], Y[, 2],
        circles = rep(r, nrow(Y)),
        fg = "blue", add = TRUE, inches = FALSE)
legend("topleft", legend = c("Data", "GTM nodes", "2*SD radius"),
       col = c("red", "green", "blue"),
       pch = c(21, 23, NA), lty = c(NA, NA, 1),
       pt.bg = c(NA, "green", NA))

cat("\nConvergence plot:\n")
plot(model, type = "convergence")

# Now fit a 2D GTM to the iris data
cat("\n\nFitting 2D GTM to iris data...\n")
data(iris)
iris_model <- GtmFit(as.matrix(iris[, 1:4]), n_iter = 50, verbose = FALSE)
print(iris_model)

cat("\nPlotting mean projection colored by species:\n")
plot(iris_model, type = "means", labels = iris$Species)

cat("\nPlotting node density:\n")
plot(iris_model, type = "density")

cat("\nDone.\n")
